Watch later
Rohan-154/flasher-video-library pull request #8
Opened 2022-05-12 07:31 UTC by Rohan-154

Add to watch later feature added.
Plz review. This PR has both add and delete feature of watch later,

2022-05-13 12:16 UTC, barbaricankit requested changes
Liked that you have used Abbreviation for reducer, also used variables in the colors.
Always try to raise a small PR.
Have suggested some changes, please look into it.

2022-05-13 12:16 UTC, barbaricankit commented on src/Components/Auth/Login/login.js
> +                      ...loginForm,
don't do things here, create a function and do things there.
If something is only of one line then do it in here.

2022-05-13 12:16 UTC, barbaricankit commented on src/Components/Fixed-Footer/footer.js
> +          <li>
why to have dummy href for anchor

2022-05-13 12:16 UTC, barbaricankit commented on src/Components/Navbar/navbar.css
> +        letter-spacing: 0;
your class name is line-height-extra and property is line-height 0

2022-05-13 12:16 UTC, barbaricankit commented on src/Components/Navbar/navbar.js
> +          </Link>
only difference I see here is Like 'to' value, so you can apply a ternary to here itself instead of entire Link tag

2022-05-13 12:16 UTC, barbaricankit commented on src/Components/VideoCard/video-card.js
> +  const { Datadispatch } = useVideo();
have variable name in camelcase.
Should be `dataDispatch`

2022-05-13 12:16 UTC, barbaricankit commented on src/Components/VideoCard/video-card.js
> +                  className={`${video.isInWatchLater && "red-color"}`}
in some cases, you are using ternary and in some cases, you are using &, have consistent things

2022-05-13 12:16 UTC, barbaricankit commented on src/Context/authContext.js
> +      console.log(email,password);
remove consoles

2022-05-15 08:45 UTC, devdeadviz approved these changes
You need to work on your code structure a lot, a lot of things are a bit messy!

2022-05-15 08:45 UTC, devdeadviz commented on src/App.js
> +import { WatchLater } from "./Pages/WatchLater/watchLater";
You can use barrel export to avoid importing different components from a single location.

2022-05-15 08:45 UTC, devdeadviz commented on src/App.js
> +        <Route path="/video/:videoId" element={<SingleVideo />} />
Add `404 page`, if user enters some wrong path.

2022-05-15 08:45 UTC, devdeadviz commented on src/Components/Navbar/navbar.js
> +            {" "}
Remove these

2022-05-15 08:45 UTC, devdeadviz commented on src/Reducer/video-reducer.js
> +          isInWatchLater: action.payload.some((item) => item._id === video._id),
try not to perform and function inside reducer, keep it simple and clean

2022-05-15 08:45 UTC, devdeadviz commented on src/Utils/likeUtils.js
> +    : postLikeHandler(token, Datadispatch, singleVideo);
Use the same naming convention everywhere!

2022-05-21 09:40 UTC, merged